### PR TITLE
Fix melodic-devel

### PR DESCRIPTION
**Pull request by henningkayser**
Replace Affine3d with Isometry3d and remove deprecated 'attempts' parameter from `RobotState::setFromIK()`.

### CODE REVIEW

**Comment by mlautman** [comment]
It seems that the moveit master branch is less functional on kinetic than previously thought

**Comment by mlautman** [comment]
Did Plus One ask for the melodic migration?

**Comment by henningkayser** [comment]
> It seems that the moveit master branch is less functional on kinetic than previously thought

What do you mean?

> Did Plus One ask for the melodic migration?

I thought Shaun agreed to do this since it just makes sense for better support and updates. Especially since there are no breaking changes and features like TOTG can be used directly without copying code.

@davetcoleman ?

**Comment by mlautman** [comment]
> What do you mean?

Ci fails with this error msg. 
``` /root/catkin_ws/src/moveit/moveit_core/collision_distance_field/src/collision_distance_field_types.cpp:55:22:   required from here
/usr/include/eigen3/Eigen/src/Geometry/Transform.h:330:5: error: static assertion failed: YOU_PERFORMED_AN_INVALID_TRANSFORMATION_CONVERSION
     EIGEN_STATIC_ASSERT(EIGEN_IMPLIES(OtherMode==int(Affine)||OtherMode==int(AffineCompact), Mode!=int(Isometry)),
     ^
```

I believe the issue is that we changed from Affine3d to Isometry3d in master

**Comment by henningkayser** [comment]
Right, all dependencies using Eigen must be compiled from source when using MoveIt melodic/master under kinetic but this can be configured with the .rosinstall.

**Comment by henningkayser** [comment]
Looks like the dependency `rosparam_handler` is missing in rosdep, though the package should work under melodic. Otherwise it's not too difficult to setup an appropriate alternative for loading parameters.

**Comment by davetcoleman** [comment]
Can we redirect this to the public fork now?

**Pull request closed without merging**
